### ISSUE TITLE
parametro sukūrimas

### ISSUE THREAD

**Issue by cerkauskas** [sauliusGTO3000/UD_Project#5]
https://github.com/sauliusGTO3000/UD_Project/blob/43c5e11d6843e1041db5c8fb7bcb798dc8e123e2/my_project/src/Controller/PostController.php#L310

kadangi ne vienoj vietoj naudoji šitą path'ą, tai galbūt vertėtų jį iškelti į parametrą services.yaml faile.

**Comment by sauliusGTO3000** [comment]
ačiū!

**Comment by sauliusGTO3000** [comment]
done
